apiVersion: v1
kind: ConfigMap
metadata:
  name: apm-server-config
  namespace: elastic-system
data:
  apm-server.yml: |
    apm-server:
      host: "0.0.0.0:8200"
      rum:
        enabled: true
      otlp:
        enabled: true 
        protocols:
          grpc:{}
          http:{}
      
      auth:
        secret_token: "Wl9sQ0xKZ0JWNlJDY3RrRTlvY0U6cWZ4X0lxX0dwQXE2TGptdkFNWEpnQQ=="  # 🔐 Add this line


    output.elasticsearch:
      hosts: ["https://es-cluster-prod-es-http.elastic-system.svc:9200"]
      username: "elastic"
      password: "5m6JUx806u5WPtlgtMw595y1"
      ssl.verification_mode: none

    setup.template.enabled: true

    logging:
      level: debug
      selectors: ["*"]
      to_stdout: true
