apiVersion: apps/v1
kind: Deployment
metadata:
  name: elastic-apm-server
  namespace: elastic-system
  labels:
    app: elastic-apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-apm-server
  template:
    metadata:
      labels:
        app: elastic-apm-server
    spec:
      containers:
        - name: apm-server
          image: vmisra1989/elastic-apm-server:9.0.2
          ports:
            - containerPort: 8200
          env:
            - name: ELASTICSEARCH_HOSTS
              value: "https://localhost:9200"
            - name: ELASTICSEARCH_USERNAME
              value: "elastic"
            - name: ELASTICSEARCH_PASSWORD
              value: "864Ftm5ztz13vXahe29Dt3f6"
            - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
              value: "/usr/share/apm-server/config/certs/ca.crt"
            - name: APM_SERVER_RUM_ENABLED
              value: "true"
          volumeMounts:
            - name: es-ca-cert
              mountPath: /usr/share/apm-server/config/certs
              readOnly: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
      volumes:
        - name: es-ca-cert
          secret:
            secretName: apm-es-ca-cert