apiVersion: v1
kind: Service
metadata:
  name: external-es
  namespace: elastic-system
spec:
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: external-es
  namespace: elastic-system
subsets:
  - addresses:
      - ip: 192.168.49.1  # 👈 Replace with your actual host IP
    ports:
      - port: 9200