apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 8.18.0
  count: 1
  image: vmisra1989/kibana:8.18.0
  elasticsearchRef:
    name: quickstart