apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: quickstart
  namespace: elastic-system
spec:
  version: 9.0.3
  image: vmisra1989/elasticsearch:9.0.3
  count: 1
  elasticsearchRef:
    name: quickstart