apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-prod
  namespace: elastic-system
spec:
  version: 9.0.2
  image: vmisra1989/kibana:9.0.2  # 👈 your custom image
  count: 1
  elasticsearchRef:
    name: es-cluster-prod
  http:
    service:
      spec:
        type: NodePort             # 👈 expose via NodePort