apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana-prod
  namespace: elastic-system
spec:
  version: 9.0.2
  count: 1
  image: vmisra1989/kibana:9.0.2
  elasticsearchRef:
    name: es-cluster-prod
  config:
    xpack.apm.enabled: true
    xpack.apm.ui.enabled: true
    xpack.apm.ui.index: "apm-*"