apiVersion: v1
kind: Service
metadata:
  name: quickstart-es-http
  namespace: elastic-system
spec:
  type: NodePort
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 30920  # Or let K8s assign it if omitted
    - name: transport
      port: 9300
      targetPort: 9300
      nodePort: 30930
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart