apiVersion: v1
kind: Service
metadata:
  name: es-nodeport
  namespace: elastic-system
spec:
  type: NodePort
  selector:
    elasticsearch.k8s.elastic.co/cluster-name: quickstart
  ports:
    - port: 9200
      targetPort: 9200
      nodePort: 30920  # Optional: omit to auto-assign
      protocol: TCP