apiVersion: v1
kind: Service
metadata:
  name: quickstart-es-http
  namespace: elastic-system
spec:
  type: NodePort
  ports:
    - name: http
      port: 9200
      targetPort: 9200
      nodePort: 30920  # Optional: can omit to auto-assign
  selector:
    common.k8s.elastic.co/type: elasticsearch
    elasticsearch.k8s.elastic.co/cluster-name: quickstart